exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - "backup"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# Site settings
title: Microservices Community
url: "https://microservices.community" # the base hostname & protocol for your site
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

comm_group_email: &comm_group_email "mailto:communication@microservices.community"
navigation_header:
  Home: /
  Join the Community: /join
  Events: /events
  Activities: /activities
  Members: /members
  Publications: /publications
  Council, Board and Committees: /boards
  Statutes: /statutes
  Contact Us: [*comm_group_email, "?subject=General Inquiry to the Microservices Community"]

# Google analytics
# ga_tracking_id: "UA-XXXX-1"